# .github/workflows/scrape-reviews.yml
name: Scrape Google Reviews

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run scraper
      env:
        OUTSCRAPER_API_KEY: ${{ secrets.OUTSCRAPER_API_KEY }}
        BUBBLE_API_TOKEN: ${{ secrets.BUBBLE_API_TOKEN }}
      run: node scraper.js
